// <auto-generated />
namespace TravelTripProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class u1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(u1));
        
        string IMigrationMetadata.Id
        {
            get { return "202410150809401_u1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
